

spring:
  datasource:
    url: jdbc:postgresql://172.30.0.1:5433/bestcommerce
    username: postgres
    password: 123456789
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: update
    open-in-view: false

#SCPRIT PARA GERAR DB
#  jpa:
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql
#          hibernate:
#            hbm2ddl:
#              delimiter: ";"

