
security:
  jwt:
    token:
      secret-key: ${API_SECRET_KEY}
      expire-length: ${API_EXPIRE_LENGTH}

spring:
  datasource:
    url: jdbc:postgresql://${DB_IP}:${DB_PORT}/${DB_NAME}
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: update
    open-in-view: false

# SCRIPT TO GENERATE DB DATA #
#  jpa:
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql
#          hibernate:
#            hbm2ddl:
#              delimiter: ";"

