cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://www.wswork.com.br

spring:
  application:
    name: best-commerce
  profiles:
    active: test

springdoc:
  pathsToMatch: /api/v1/**
  swagger-ui:
    use-root-path: true